<?php
echo '<?php'
?>

namespace <?php echo $block->getData('vendor') ?>\<?php echo $block->getData('module') ?>\Test\Unit;

use \PHPUnit\Framework\TestCase;
use \Magento\Framework\TestFramework\Unit\Helper\ObjectManager;

class SampleTest extends \PHPUnit\Framework\TestCase
{
    private $objectManager;

    public function setUp()
    {
        $this->objectManager = new ObjectManager($this);
        $this->sampleClass = $this->objectManager->getObject('<?php echo $block->getData('vendor') ?>\<?php echo $block->getData('module') ?>\Model\SampleModel');
    }

    /**
     * @test
     */
    public function testUnitTests()
    {
        $this->assertTrue(true);
    }

    /**
     * @test
     */
    public function testSampleClass()
    {
        $result = $this->sampleClass->getSampleTestValue();
        $this->assertEquals($result, "Hello World!");
    }
}
