<?php echo '<?xml version="1.0"?>' ?>

<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title><?php echo $block->getData('vendor') ?> <?php echo $block->getData('extension') ?></title> <!-- your theme's name -->
    <parent>Magento/backend</parent> <!-- the parent theme, in case your theme inherits from an existing theme -->
</theme>
