<?php echo '<?xml version="1.0"?>' ?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
    <menu>
        <add id="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::manager" title="Sample Menu" module="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>" sortOrder="10" resource="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::manager"/>
        <add id="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::sample" title="Sample Index" module="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>" sortOrder="0" resource="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::sample" parent="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::manager"
            action="sample/sample/index" translate="title" />
    </menu>
</config>
