<?php echo '<?xml version="1.0"?>' ?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="standard">
        <route id="sample" frontName="sample">
            <module name="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('extension') ?>" />
        </route>
    </router>
</config>
