<?php echo '<?xml version="1.0"?>' ?>
<!--
/**
 * created with Codever Magento Scaffolder.
 *
 * @category  Sample
 * @package   <?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="<?php echo $block->getData('vendor') ?>_<?php echo $block->getData('module') ?>::sample" title="Sample Index" sortOrder="10" />
            </resource>
        </resources>
    </acl>
</config>
