{
  "name": "<?php echo strtolower($block->getData('vendor')) ?>/<?php echo strtolower($block->getData('extension')) ?>",
  "description": "",
  "require": {
    "php": "~7.4.0||~8.1.0",
    "magento/theme-frontend-blank": "100.0.*",
    "magento/framework": "100.0.*"
  },
  "type": "magento2-theme",
  "version": "1.0.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "authors": [
    {
      "name": "",
      "email": "",
      "homepage": "",
      "role": ""
    }
  ],
  "autoload": {
    "files": [
      "registration.php"
    ]
  }
}
