{
  "name": "<?php echo strtolower($this->getData('vendor')) ?>/<?php echo strtolower($this->getData('module')) ?>",
  "description": "",
  "require": {
    "php": "~7.4.0||~8.1.0"
  },
  "type": "magento2-module",
  "version": "1.0.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "authors": [
    {
      "name": "",
      "email": "",
      "homepage": "",
      "role": ""
    }
  ],
  "autoload": {
    "files": [
      "registration.php"
    ],
    "psr-4": {
      "<?php echo $this->getData('vendor') ?>\\<?php echo $this->getData('module') ?>\\": ""
    }
  }
}
